### PR TITLE
add acceleration for drift

### PR DESCRIPTION
**Pull request by kifhan**
I wrap the vehicle body with Kinematic Body.
It makes the vehicle be able to drift. (sort of)
I'm not sure it is the best way or right way, but I will keep searching for it.
Other possible approach is fork the VehichleBody Class from Source to make new driftable vehicle body class.

### CODE REVIEW

**Comment by Zireael07** [comment]
That's a really neat solution, I think I'm gonna borrow it for my car game :P

**Comment by Zireael07** [comment]
Why close?

**Comment by kifhan** [comment]
Oh, I found it problem on this solution. So I thought better close it, before fixing it.

Problem:
If you using engine_force on BehicleBody, It moves separately from its wrap KinematicBody. It make very weird behavior.
If you want to do it properly with KinematicBody wrap, better not using engine_force and use move function on KinematicBody only.
Then you need to calculate physics stuffs like friction on the tires, acceleration by center of weight.
For me, It's kind of way over my knowledge level right now. So I may need some time to digest.

FYI:
[Arcade Vehicle Physics Tour](https://www.youtube.com/watch?v=LG1CtlFRmpU&t=302s)

**Comment by davismiculis** [comment]
Also currently the current vehicle behaviour is set as "normal" handling, although I experimented with vehicle body and wheel properties I got somewhat more drifting handling. Should I add that handling?

**Comment by kifhan** [comment]
@davismiculis Could you upload that on new branch?

**Comment by davismiculis** [comment]
@kifhan what I wrote above, current handling behaves "normal" but I also can add my "drift" handling based on vehicle body and wheels, which I used previously.

**Comment by kifhan** [comment]
@davismiculis If it is works fine, why not?

**Comment by davismiculis** [comment]
Hey, I just commited my drift handling (13644711), it uses native funcionality without the acceleration body.

Testing out your way of drifting, I kinda don't see much improvement, is there something I'm missing?

**Comment by michhhh** [comment]
I added it but without this MR, because of the conflicts and binary scenes.

**Pull request closed without merging**
